### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'storagePolicy'

### ISSUE THREAD

**Issue by robberphex** [jingw/pyhdfs#1]
I am using hadoop 2.6( with [Docker](https://registry.hub.docker.com/u/sequenceiq/hadoop-docker/): `sudo docker run -i -t sequenceiq/hadoop-docker:2.6.0 /etc/bootstrap.sh -bash`).

When I using PyHDFS to call `client.list_status`, I got error:

```
Traceback (most recent call last):
  File "testhdfs.py", line 3, in <module>
    print(client.list_status('/'))
  File "...testenv/lib/python3.4/site-packages/pyhdfs.py", line 428, in list_status
    _json(self._get(path, 'LISTSTATUS', **kwargs))['FileStatuses']['FileStatus']
  File "...testenv/lib/python3.4/site-packages/pyhdfs.py", line 427, in <listcomp>
    FileStatus(**item) for item in
TypeError: __new__() got an unexpected keyword argument 'storagePolicy'
```

The code:

```
from pyhdfs import HdfsClient
client = HdfsClient(hosts='172.17.0.2:50070')
print(client.list_status('/'))
```

This issue is cause of JSON from server has extra property `storagePolicy`, add it to [pyhdfs.py](https://github.com/jingw/pyhdfs/blob/dc5f7d0401c78cfe1a30e6a73087bf2713bf1bd8/pyhdfs.py#L155) can fix this. But I want to know weather this property is standard property of HDFS/WebHDFS.

**Comment by jingw** [comment]
I can't find storagePolicy in the latest docs for WebHDFS (http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html). However, it looks like archival storage was added recently in Hadoop 2.6, and I only tested against the CDH QuickStart VM (Hadoop 2.5), so it's possible they just haven't fixed the WebHDFS docs.

In any case, I should make the client tolerant of getting extra attributes, so it doesn't break on Hadoop upgrades. Thanks for the heads up.
