### ISSUE TITLE
"copy_to_local" don't have override option.

### ISSUE THREAD

**Issue by yiershanxll** [jingw/pyhdfs#16]
the function copy_to_local  and copy_from_local don't have override option.How should I set?

**Comment by yiershanxll** [comment]
can you add a option about override?

**Comment by yiershanxll** [comment]
thank you very much

**Comment by jingw** [comment]
I presume by "override" you mean overwriting existing files. For copy_to_local, that's what it currently does. For copy_from_local, take a look at the documentation: "Takes all arguments that :py:meth:`create` takes."

If you meant something else, could you be more specific and submit a pull request?
