### ISSUE TITLE
Is it possible to support 'getmerge'?

### ISSUE THREAD

**Issue by YodesYang** [jingw/pyhdfs#19]
Such as title. 
[getmerge](https://hadoop.apache.org/docs/r1.0.4/cn/hdfs_shell.html#getmerge): download all the files in the path and aggregate them into one.

**Comment by jingw** [comment]
Hi, the getmerge command isn't anything special. It just loops through all the files and copies them. It's a client-side feature, not a server-side RPC. There's no WebHDFS endpoint for it.
https://github.com/apache/hadoop/blob/03cfc852791c14fad39db4e5b14104a276c08e59/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/shell/CopyCommands.java#L101


You can implement this yourself with something along the lines of
```
with open('dest', 'w') as f:
    with hdfs.open('thing') as f2:
        f.write(f2.read())
```
